setup:
  name: ours-cxatt_monodepth
  model:
    backbone: resnet101
    use_dilation: [False, False, True]
    pretrain: mono_cityscapes_1024x512_r101dil_aspp_dec6_lr5_fd2_crop512x512bs4
    feature_dist: False
    freeze_backbone: False
    pose_kwargs:
      pose_model_input: pairs
      frame_ids: [0, -1, 1]
      provide_uncropped_for_pose: False
      # freeze: True
    tasks:
      semseg:
        head: padnet+
        kwargs:
          aspp_rates: [6, 12, 18]
          intermediate_aspp: True
          num_ch_dec: [64, 128, 128, 256, 256]
          num_out_ch: 16
          active_scales: [0, 2]
      disp:
        head: padnet+
        kwargs:
          aspp_rates: [6, 12, 18]
          intermediate_aspp: True
          num_ch_dec: [64, 128, 128, 256, 256]
          is_regression: True
          num_out_ch: 1
          active_scales: [0, 1, 2, 3]
  kwargs:
    ablation: ['SA', 'SxTAM', 'add']
    enc_layers: [[4, 3, 2, 1], [0]]
    stages: [1]
  loss:
    tasks:
      semseg:
        loss: cross_entropy
        kwargs:
          scales: [0, 2]
          weight: 1
          n_classes: 16
      disp:
        loss: ssde
        kwargs:
          scales: [0, 1, 2, 3]
          weight: 1
          min_depth: 0.1
          max_depth: 100
          test_min_depth: 1.0e-3
          test_max_depth: 80
          disparity_smoothness: 1.0e-3
          no_ssim: False
          avg_reprojection: False
          disable_automasking: False

          # duplicates from other parts of cfg
          batch_size: 2
          frame_ids: [0, -1, 1]
          width: 1024
          height: 512
          crop_w: 512
          crop_h: 512

    kwargs:
      baselines:
        semseg: 0.78
        disp: 5.33
      gammas:
        semseg: 0
        disp: 1
  lr:
    main.backbone: 0.00001
    default: 0.00005
    monodepth.pose_net: 0.000001

training:
  logdir: $ENV:LOG_DIR/
  n_workers: 2
  seed: 42
  shuffle_trainset: True
  iterations: 40_000
  val_interval:
    '0': 100
    '100': 2500
    '30000': 1000
  use_amp: False
  benchmark: True
  detect_anomaly: False
  print_interval: 100
  resume: null
  save_model: False
  save_finished_model: True

data:
  load_sequences: True
  load_semantic_gt: True
  n_classes: 16
  train_bs: 2
  valid_bs: 2
  n_valid_logged: 2
  n_train_logged: 2
  dataset_seed: 42
  dataset: cityscapes
  path: $ENV:CITYSCAPES_DIR
  frame_ids: [0, -1, 1]
  num_scales: 4
  width: 1024
  height: 512
  crop_w: 512
  crop_h: 512
  augmentations:
    random_horizontal_flip: 0.5
  color_full_scale: 0
  only_sequences_with_segmentation: True
  restrict_to_subset:
  val_downsample_gt: True
  src_split: train
  val_split: val
  inverse_depth: True

optim:
  name: Adam
  kwargs:
    betas: [0.9, 0.999]
  clip_grad_norm: 10

scheduler:
  name: step
  kwargs:
    step_size: 30_000
    gamma: 0.1
